config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'users/index'

  get 'users/show' 

  get 'resources/show'

  get 'outlines/show'

  get 'years/index'

  get 'years/show'

  get 'classrooms/index'

  get 'classrooms/show'

  get 'classrooms/mates'

  get 'homes/index'

  
  mount Commontator::Engine => '/commontator'
  mount LetsEncrypt::Engine => '/.well-known'

  mathjax 'mathjax'

   root 'homes#index'

  resources :questions
  resources :years
  resources :classrooms
  resources :blogs
  resources :resources
  resources :outlines
  resources :users
  resources :parts

  resources :years do
    resources :classrooms, :title, :id
  end

  resources :classrooms do
    resources :title, :id, :body, :year_id
  end

  resources :blogs do
    resources :title, :id, :body, :blopic, :writer
  end

  resources :resources do
      resources :title, :id, :body, :classrooms_id
  end

  resources :outlines do
      resources :title, :id, :body, :classrooms_id
  end
  resources :questions do
      resources :title, :id, :body, :classrooms_id
  end
  resources :parts do
      resources :title, :id, :body, :questions_id
  end

  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	acts_as_commontable
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	acts_as_commontable
	
    has_many :outlines
    accepts_nested_attributes_for :outlines
    has_many :sems
    accepts_nested_attributes_for :sems
    has_many :resources
    accepts_nested_attributes_for :resources
    has_many :questions
    accepts_nested_attributes_for :questions
    belongs_to :year
	accepts_nested_attributes_for :year


    has_many :users


end

app/models/outline.rb
class Outline < ActiveRecord::Base
	belongs_to :sem
	accepts_nested_attributes_for :sem
end

app/models/part.rb
class Part < ActiveRecord::Base
	belongs_to :question
	accepts_nested_attributes_for :question
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to :user
	belongs_to :classroom
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :classroom
	accepts_nested_attributes_for :classroom
	has_many :parts
    accepts_nested_attributes_for :parts
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	belongs_to :classroom
	accepts_nested_attributes_for :classroom
end

app/models/sem.rb
class Sem < ApplicationRecord
	has_many :outlines
    accepts_nested_attributes_for :outlines
    belongs_to :classroom
	accepts_nested_attributes_for :classroom

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_commontator

   def user_params
      params.require(:user).permit(:user_name, :paid, :whatsapp, :major, :level, :minor, :email, :password, :password_confirmation)
   end   

end

app/models/year.rb
class Year < ActiveRecord::Base
	has_many :classrooms
	accepts_nested_attributes_for :classrooms
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :authenticate_user!
  def index
  end
  def show
  	@question = Question.find(params[:id])
  	@questions = Question.all
    @parts = Part.all
  	@classroom = Classroom.find(params[:id])
    @classrooms = Classroom.all
    
  end

  def create
  	Question.create(params[:question])
  end

  def update
  	question = current_account.questions.find(params[:id])
  	question.update!(question_params)
  	redirect_to question
  end

private
  def question_params
    params.require(:question).permit(:title, :body, :id)
    params.require(:classroom).permit(:classroom_id)
    params.require(:part).permit(:part_id)
  end   
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/outlines_helper.rb
module OutlinesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/questions/show.html.erb
  <!-- Navigation -->
  <div id="navigation" class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#intro">Pascology</a>
        </div>

        <div class="navigation">
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <nav>
              <ul class="nav navbar-nav navbar-right">
                <li class="current"><%= link_to 'HOME',homes_index_path %></li>
                <li class="current"><%= link_to 'COURSES',years_index_path %></li>
                <li> <% if current_user %>
                    <%= link_to 'LOGOUT', '/users/sign_out' %>
                    <% else %></li>
                    <li>  <%= link_to 'LOGIN', '/users/sign_in' %></li>
                    <li> <%= link_to 'SIGNUP', '/users/sign_up' %></li>
                    <% end %>
              </ul>
            </nav>
          </div>
          <!-- /.navbar-collapse -->
        </div>

      </div>
    </div>
  <!-- /Navigation -->
    <br>
    <br>
    <br>
    <br>
    <div class="container">
    <% if current_user.paid ==1 %>		
      <% for part in @question.parts %>
        <%= link_to (part.title), part_path(part), :class => "btn btn-default btn-lg col-lg-6" %>
      <% end %>
    <% else %>
      <section id="pricing" class="section-bg">
        <div class="row">
          <div class="col-lg-6 col-md-6">
            <div class="box featured" data-aos="fade-right">
              <h3>MONTHLY SUBSCRIPTION</h3>
              <h4><sup>GHS</sup>60.00</h4>
              <ul>
                <li><h6>PDFs</h6> </li>
                <li><h6> STUDY NOTES</h6></li>
                <li><h6>LECTURE VIDEOS</h6></li>
                <li><h6>TRY QUESTIONS AND ANSWRES</h6></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <div class="box featured" data-aos="fade-right">
              <h3>MTN MOBILE MONEY PAYMENT</h3>
              <h4><sup>MTN</sup>054 360 0823</h4>
              <ul>
                <li><h6>A monthly subcription gives you access to all features for all courses across all year groups (level 100 - level 400)</h6> </li>
                <li><h6> Kindly whatsapp or call this number to confirm payment. Thank you.</h6></li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <% end %>
    	
        	<br>
    </div>
    <br>
<div class="herog text-center">
<a><%= link_to "Back", :back, :class => "btn btn-lg" %></a>
</div>
<br>