config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'users/index'

  get 'users/show' 

  get 'resources/show'

  get 'outlines/show'

  get 'years/index'

  get 'years/show'

  get 'classrooms/index'

  get 'classrooms/show'

  get 'classrooms/mates'

  get 'homes/index'

  
  mount Commontator::Engine => '/commontator'
  mount LetsEncrypt::Engine => '/.well-known'

  mathjax 'mathjax'

   root 'homes#index'

  resources :questions
  resources :years
  resources :classrooms
  resources :blogs
  resources :resources
  resources :outlines
  resources :users
  resources :parts

  resources :years do
    resources :classrooms, :title, :id
  end

  resources :classrooms do
    resources :title, :id, :body, :year_id
  end

  resources :blogs do
    resources :title, :id, :body, :blopic, :writer
  end

  resources :resources do
      resources :title, :id, :body, :classrooms_id
  end

  resources :outlines do
      resources :title, :id, :body, :classrooms_id
  end
  resources :questions do
      resources :title, :id, :body, :classrooms_id
  end
  resources :parts do
      resources :title, :id, :body, :questions_id
  end

  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	acts_as_commontable
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	acts_as_commontable
	
    has_many :outlines
    accepts_nested_attributes_for :outlines
    has_many :sems
    accepts_nested_attributes_for :sems
    has_many :resources
    accepts_nested_attributes_for :resources
    has_many :questions
    accepts_nested_attributes_for :questions
    belongs_to :year
	accepts_nested_attributes_for :year


    has_many :users


end

app/models/outline.rb
class Outline < ActiveRecord::Base
	belongs_to :sem
	accepts_nested_attributes_for :sem
end

app/models/part.rb
class Part < ActiveRecord::Base
	belongs_to :question
	accepts_nested_attributes_for :question
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to :user
	belongs_to :classroom
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :classroom
	accepts_nested_attributes_for :classroom
	has_many :parts
    accepts_nested_attributes_for :parts
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	belongs_to :classroom
	accepts_nested_attributes_for :classroom
end

app/models/sem.rb
class Sem < ApplicationRecord
	has_many :outlines
    accepts_nested_attributes_for :outlines
    belongs_to :classroom
	accepts_nested_attributes_for :classroom

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_commontator

   def user_params
      params.require(:user).permit(:user_name, :paid, :whatsapp, :major, :level, :minor, :email, :password, :password_confirmation)
   end   

end

app/models/year.rb
class Year < ActiveRecord::Base
	has_many :classrooms
	accepts_nested_attributes_for :classrooms
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
    @blogs = Blog.all
    commontator_thread_show(@blog)
  end

  def create
    Blog.create(params[:blog])
  end
  
  def update
    blog = current_account.blogs.find(params[:id])
	  blog.update!(blog_params)
	  redirect_to blog
  end
  
private
  def blog_params
    params.require(:blog).permit(:title, :body, :id, :writer, :blopic)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/outlines_helper.rb
module OutlinesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/blogs/index.html.erb
<br>
<br>
<br>
<br>
<br>
    <div class="container">
     <h1 class="text-left"><strong> Welcome <% if current_user %><%= current_user.user_name %><% end %> </strong> </h1>
    <br>
    <h1 class="text-center"></h1>
    <div class="row" id="features">
    	<% for blog in @blogs %>
				<div class="col-sm-4 feature">
						<%= raw(blog.blopic) %>
						<h2 class="text-center"><%= link_to blog.title, blog_path(blog) %></h2>
                        <h6 class="text-muted text-right"><%= blog.writer %></h6>						
				</div><!-- end feature -->
		<% end %>
    </div>
    
            </div>
    

app/views/blogs/show.html.erb
    <br>
    <br>
    <br>
    <br>
    <br>
    	<div class="container">
    		<p><%= raw(@blog.body) %></p>
    		<br>
        	         
        	<br>
            <%= commontator_thread(@blog) %>
            <br>
           <p> <% if current_user %>
                    <%= current_user.user_name %>, you're awesome ;-). We are waiting for your wise words of wisdom.</p>
                    <% else %>
                    <%= link_to 'LOGIN', '/users/sign_in' %>
                    <% end %>
        </div>
    <br>
<div class="text-center">
<%= link_to "Back", :back, :class => "btn btn-default btn-lg" %>
</div>
<br>