config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'users/index'

  get 'users/show' 

  get 'resources/show'

  get 'outlines/show'

  get 'years/index'

  get 'years/show'

  get 'classrooms/index'

  get 'classrooms/show'

  get 'classrooms/mates'

  get 'homes/index'

  
  mount Commontator::Engine => '/commontator'
  mount LetsEncrypt::Engine => '/.well-known'

  mathjax 'mathjax'

   root 'homes#index'

  resources :questions
  resources :years
  resources :classrooms
  resources :blogs
  resources :resources
  resources :outlines
  resources :users
  resources :parts

  resources :years do
    resources :classrooms, :title, :id
  end

  resources :classrooms do
    resources :title, :id, :body, :year_id
  end

  resources :blogs do
    resources :title, :id, :body, :blopic, :writer
  end

  resources :resources do
      resources :title, :id, :body, :classrooms_id
  end

  resources :outlines do
      resources :title, :id, :body, :classrooms_id
  end
  resources :questions do
      resources :title, :id, :body, :classrooms_id
  end
  resources :parts do
      resources :title, :id, :body, :questions_id
  end

  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	acts_as_commontable
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	acts_as_commontable
	
    has_many :outlines
    accepts_nested_attributes_for :outlines
    has_many :sems
    accepts_nested_attributes_for :sems
    has_many :resources
    accepts_nested_attributes_for :resources
    has_many :questions
    accepts_nested_attributes_for :questions
    belongs_to :year
	accepts_nested_attributes_for :year


    has_many :users


end

app/models/outline.rb
class Outline < ActiveRecord::Base
	belongs_to :sem
	accepts_nested_attributes_for :sem
end

app/models/part.rb
class Part < ActiveRecord::Base
	belongs_to :question
	accepts_nested_attributes_for :question
end

app/models/payment.rb
class Payment < ApplicationRecord
	belongs_to :user
	belongs_to :classroom
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :classroom
	accepts_nested_attributes_for :classroom
	has_many :parts
    accepts_nested_attributes_for :parts
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	belongs_to :classroom
	accepts_nested_attributes_for :classroom
end

app/models/sem.rb
class Sem < ApplicationRecord
	has_many :outlines
    accepts_nested_attributes_for :outlines
    belongs_to :classroom
	accepts_nested_attributes_for :classroom

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_commontator

   def user_params
      params.require(:user).permit(:user_name, :paid, :whatsapp, :major, :level, :minor, :email, :password, :password_confirmation)
   end   

end

app/models/year.rb
class Year < ActiveRecord::Base
	has_many :classrooms
	accepts_nested_attributes_for :classrooms
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  before_action :authenticate_user!
  def index
    @years = Year.all
  	@classrooms = Classroom.all
  end 

  def show
  	@years = Year.all
  	@year = Year.find(params[:id])
  	@classrooms = Classroom.all
  	@Classroom = Classroom.find(params[:id])
  end

  def create
  	year.create(params[:year])
  end

  def update
  	year = current_account.year.find(params[:id])
  	year.update!(year_params)
  	redirect_to year
  end

private
  def year_params
  	params.require(:year).permit(:title)
  	params.require(:classroom).permit(:title, :classroom_id)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/outlines_helper.rb
module OutlinesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/index.html.erb
  <!-- Navigation -->
  <div id="navigation" class="navbar navbar-fixed-top navbar-default" role="navigation">
      <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#intro">Pascology</a>
        </div>

        <div class="navigation">
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <nav>
              <ul class="nav navbar-nav navbar-right">
                <li class="current"><%= link_to 'HOME',homes_index_path %></li>
                <li> <% if current_user %>
                    <%= link_to 'LOGOUT', '/users/sign_out' %>
                    <% else %></li>
                    <li>  <%= link_to 'LOGIN', '/users/sign_in' %></li>
                    <li> <%= link_to 'SIGNUP', '/users/sign_up' %></li>
                    <% end %>
              </ul>
            </nav>
          </div>
          <!-- /.navbar-collapse -->
        </div>

      </div>
    </div>
  <!-- /Navigation -->
<br>
<br>
<br>
<br>
<br>
<div class="container text-center">
    <h2><strong>Welcome <%= current_user.user_name %></strong></h2>

<% @years.each do |year| %>

<div class="goldfish container text-center ">
 <div class="row">
  <div class="col-md-12">
   <div class="row">
    <div class="spidey">
     <table class="table table-striped">
      <thead>
       <tr><th class="text-center"><h5><%= year.title%></h5></th></tr>
      </thead>
      <tbody>
       <% year.classrooms.order(created_at: :asc).each do |classroom| %>
        <tr><td><a><%= link_to classroom.title, classroom_path(classroom)%></a></td></tr>
       <% end %>
       <br>
      </tbody>
     </table>
    </div>
   </div>
  </div>
 </div>
</div>
<% end %>
</div>